### ISSUE TITLE
File don't exist

### ISSUE THREAD

**Issue by Rusfell** [tsackton/ratite-genomics#2]
Hi.
I am trying to follow your pipline with the ratite-genomics, but i found a script don't exist in the folder.

in  `ratite-genomics/04_wga/02_ce_id/run_phast.sh` line 183, you write:

> ./keep_ref_only.pl $MAF &

but i can not find this `keep_ref_only.pl`.

Could please upload this script?

Thanks!!

**Comment by tsackton** [comment]
I don't have any code from this project anymore that is not in the repository, unfortunately, it must have gotten accidentally deleted or moved at some point.

**Comment by Rusfell** [comment]
Thanks for your reply~

**Comment by Rusfell** [comment]
Thanks for your reply~

> I don't have any code from this project anymore that is not in the repository, unfortunately, it must have gotten accidentally deleted or moved at some point.

Thanks for your reply~

**Comment by aaannaw** [comment]
@tsackton @Rusfell 
Hi
Could you tell me  what is this script used to achieve and I would write a script for the goal myself. I can not understand the  description for the script  "remove chicken lines that are from scaffolds other than target with perl script"  in the https://github.com/tsackton/ratite-genomics/blob/master/04_wga/02_ce_id/run_phast.sh. 
![image](https://github.com/user-attachments/assets/9f86bf2c-0ed1-4514-ad31-78f5ea451792)
Looking forward with your reply!
Best wishes!
Na Wan

**Comment by tsackton** [comment]
This is an obsolete step due to an old version of the hal2maf code. If you use modern approaches to project a hal to a maf this should not be necessary.
